### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by CJYKK**
Can you help me add it to all branches?

### CODE REVIEW

**Comment by SuperMartijn642** [comment]
Thank you for the translations!

No worries about the other branches. Since it's just a new file, I can easily just cherry pick it for the other branches.

I am currently on vacation, so it will be a bit before I merge it.

**Comment by CJYKK** [comment]
This mod is very good. Have a nice vacation!

**Comment by CJYKK** [comment]
> Thank you for the translations!
> 
> No worries about the other branches. Since it's just a new file, I can easily just cherry pick it for the other branches.
> 
> I am currently on vacation, so it will be a bit before I merge it.

This mod is very good. Have a nice vacation!

**Comment by SuperMartijn642** [comment]
Sorry for the long wait, finally getting around to merging these now.
The translations will be available in Durability Tooltip 1.1.2.

Thanks again for the translations!

**Pull request merged**
